### ISSUE TITLE
Bug: source code invisible

### ISSUE THREAD

**Issue by nat-418** [trimental/inlyne#97] opened 2023-05-09 08:17 UTC
Source code marked with single backticks is not displayed properly.

For example, given the markdown:

    # Test

    `foo`

    ```
    bar
    ```

We get this output:

![image](https://user-images.githubusercontent.com/93013864/237036875-0cdda152-5785-4048-9385-3ef87021be28.png)

**Comment by nicoburns** [comment] 2023-05-09 19:45
I'm also seeing weirdly low contrast text in code blocks:

<img width="739" alt="Screenshot 2023-05-09 at 20 45 07" src="https://github.com/trimental/inlyne/assets/1007307/a5ab5b9f-b90f-4e0b-85f2-a8dca8280910">


Test file: https://github.com/DioxusLabs/taffy/blob/main/README.md

**Comment by trimental** [comment] 2023-05-09 19:48
Thanks for providing this issue. It's on my bucket list.

**Comment by CosmicHorrorDev** [comment] 2023-05-09 19:55
@nat-418 What version of `inlyne` are you using? I can reproduce on v0.2.1, but not v0.3.0

![image](https://github.com/trimental/inlyne/assets/30302768/68d0f8e6-46f9-4ada-932d-3d65bea794a6)

---

@nicoburns That's probably just from bad defaults for the codeblock background color with the default syntax highlighting theme (Edit: I see you already likely noticed that). We should definitely tweak the defaults for both dark and light theme to make sure that they're easy to read

Alternatively I think we can get the background color from the syntax theme since it's normally included. We currently have it specified separately

**Comment by nat-418** [comment] 2023-05-10 08:32
> @nat-418 What version of `inlyne` are you using? I can reproduce on v0.2.1, but not v0.3.0
> 
> ![image](https://user-images.githubusercontent.com/30302768/237205884-68d0f8e6-46f9-4ada-932d-3d65bea794a6.png)
> 
> @nicoburns That's probably just from bad defaults for the codeblock background color with the default syntax highlighting theme. We should definitely tweak the defaults for both dark and light theme to make sure that they're easy to read
> 
> Alternatively I think we can get the background color from the syntax theme since it's normally included. We currently have it specified separately

inlyne v0.2.1 (from Nix package repository)

**Comment by CosmicHorrorDev** [comment] 2023-05-10 13:31
The update to v0.3.1 just got merged into nixpkgs earlier today, so I'd imagine it should be available in unstable here soon. Feel free to reopen this if you notice the same issue on newer versions 👍

**Closed** 2023-05-10 13:32 UTC
